#!/usr/bin/env python3
"""
Phase 6: Generate final review report.

Summarizes translation pipeline results: counts, per-file stats,
remaining CJK characters, and flagged translations.

Usage:
    python scripts/i18n/report.py [--output PATH]
"""
import argparse
import json
import re
import sys
from pathlib import Path
from collections import defaultdict

CJK_RE = re.compile(r'[\u4e00-\u9fff]')


def count_cjk_in_file(file_path: Path) -> int:
    """Count remaining CJK characters in a file."""
    try:
        content = file_path.read_text(encoding='utf-8')
        return len(CJK_RE.findall(content))
    except (IOError, UnicodeDecodeError):
        return -1


def main():
    parser = argparse.ArgumentParser(description="Generate translation pipeline report")
    parser.add_argument("--output", "-o", default="scripts/i18n/output/final_report.md",
                        help="Output report path")
    parser.add_argument("--segments", default="scripts/i18n/output/segments.jsonl")
    parser.add_argument("--translations", default="scripts/i18n/output/translations_validated.jsonl")
    args = parser.parse_args()
    
    script_dir = Path(__file__).resolve().parent
    project_root = script_dir.parent.parent
    
    segments_path = project_root / args.segments
    translations_path = project_root / args.translations
    output_path = project_root / args.output
    
    # Load data
    segments = []
    if segments_path.exists():
        with open(segments_path, 'r', encoding='utf-8') as f:
            segments = [json.loads(l) for l in f if l.strip()]
    
    translations = []
    if translations_path.exists():
        with open(translations_path, 'r', encoding='utf-8') as f:
            translations = [json.loads(l) for l in f if l.strip()]
    
    # Compute stats
    files_in_segments = sorted(set(s["file"] for s in segments))
    
    status_counts = defaultdict(int)
    for t in translations:
        status_counts[t.get("status", "unknown")] += 1
    
    # Check remaining CJK per file
    file_cjk_counts = {}
    for rel_path in files_in_segments:
        file_path = project_root / rel_path
        file_cjk_counts[rel_path] = count_cjk_in_file(file_path)
    
    # Write report
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("# MiroFish Backend Translation — Final Report\n\n")
        
        # Pipeline summary
        f.write("## Pipeline Summary\n\n")
        f.write(f"- **Segments extracted:** {len(segments)}\n")
        f.write(f"- **Translations received:** {len(translations)}\n")
        f.write(f"- **Auto-accepted:** {status_counts['auto-accepted']}\n")
        f.write(f"- **Spot-check:** {status_counts['spot-check']}\n")
        f.write(f"- **Manual review:** {status_counts['manual-review']}\n")
        f.write(f"- **Rejected:** {status_counts['rejected']}\n")
        f.write(f"- **Files scanned:** {len(files_in_segments)}\n")
        f.write("\n")
        
        # Per-file CJK remaining
        f.write("## Remaining CJK Characters per File\n\n")
        f.write("| File | CJK Remaining | Status |\n")
        f.write("|------|--------------|--------|\n")
        
        total_remaining = 0
        for rel_path in files_in_segments:
            count = file_cjk_counts.get(rel_path, -1)
            if count < 0:
                status = "⚠️ error"
            elif count == 0:
                status = "✅ done"
            elif count < 10:
                status = "🟡 almost"
            else:
                status = "🔴 remaining"
            total_remaining += max(0, count)
            f.write(f"| {rel_path} | {count} | {status} |\n")
        
        f.write(f"\n**Total remaining CJK characters: {total_remaining}**\n\n")
        
        # Coverage
        if len(segments) > 0:
            coverage = (status_counts['auto-accepted'] + status_counts['spot-check']) / len(segments) * 100
            f.write(f"**Translation coverage: {coverage:.1f}%**\n\n")
        
        f.write("---\n")
        f.write("Generated by `scripts/i18n/report.py`\n")
    
    print(f"Report written to: {output_path}")
    print(f"\nQuick stats:")
    print(f"  Segments: {len(segments)}")
    print(f"  Translated: {len(translations)}")
    print(f"  Remaining CJK total: {total_remaining}")
    
    # Files still needing work
    needs_work = [f for f, c in file_cjk_counts.items() if c > 0]
    if needs_work:
        print(f"\n  Files still with CJK ({len(needs_work)}):")
        for f in needs_work[:10]:
            print(f"    {f}: {file_cjk_counts[f]} chars")


if __name__ == "__main__":
    main()
